export * from './respMovieDataInterface'
export * from './respGenreDataInterface'
export * from './genreInterface'
export * from './prod_companiesInterface'
export * from './prod_countriesInterface'
export * from './spoken_langInterface'
export * from './movieInterface'
