
export * from './respGenresInterface'
export * from './genreInterface'
export * from './prod_companiesInterface'
export * from './prod_countriesInterface'
export * from './spoken_langInterface'
export * from './movieInterface'
export * from './paginationInterface'
export * from './movieVideosInterface'
export * from './movieVideoInterface'